name: Publish
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NAME: tachidesk-flutter-${GITHUB_REF#refs/tags/}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "beta"
      - name: Build
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter config --enable-linux-desktop
          flutter build linux --release

      - name: Package
        run: tar --transform s/bundle/$NAME-linux-x64/ -cvf - \
          -C build/linux/x64/release bundle | gzip -9 - > $NAME-linux-x64.tar.gz

      - run: ls -la

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: $NAME-linux-x64
