name: Publish release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
         channel: 'beta'
      - id: get_version
        uses: battila7/get-version-action@v2
         
      - run: |
         sudo apt-get update -y
         sudo apt-get install -y ninja-build libgtk-3-dev zip
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux --release
      - run: |
         bundle="Tachidesk-Flutter-linux-x64-${{steps.get_version.outputs.version}}"
         mv build/linux/x64/release/bundle "$bundle"
         tar -cvf - "$bundle" | gzip -9 - > "$bundle.tar.gz"
      - run: ls -la
