name: Publish
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # see https://github.com/softprops/action-gh-release
    steps:
      # - name: Set environment variables
      #   run: echo "name=tachidesk-flutter-${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "beta"
      - name: Build
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter config --enable-linux-desktop
          flutter build linux --release

      - name: Package
        run: |
          pkg="tachidesk-flutter-${GITHUB_REF#refs/tags/}-linux-x64"
          tar --transform "s/bundle/$pkg/" -cvf - \
            -C build/linux/x64/release bundle | gzip -9 - > "$pkg.tar.gz"

      - run: ls -la

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: tachidesk-flutter-*
