name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
         channel: 'beta'
      - id: get_version
        uses: battila7/get-version-action@v2
      
      - name: Build
        run: |
         sudo apt-get update -y
         sudo apt-get install -y ninja-build libgtk-3-dev zip
         flutter config --enable-linux-desktop
         flutter build linux --release

      - name: Package 
        run: |
         bundle="Tachidesk-Flutter-linux-x64-${{steps.get_version.outputs.version-without-v}}"
         tar -C build/linux/x64/release/bundle --transform s/bundle/$bundle/ -cvf - "$bundle" | gzip -9 - > "$bundle.tar.gz"
        run: ls -la
    
      - name: Upload
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "$bundle.tar.gz"
          tags: true
          draft: true
          verbose: true

