name: Publish
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    permissions:
      contents: write      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
           
      - name: Build
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev zip
          flutter config --enable-linux-desktop
          flutter build linux --release

      - name: Package 
        run: |
          bundle="Tachidesk-Flutter-linux-x64-${GITHUB_REF#refs/tags/}"
          tar -C build/linux/x64/release --transform s/bundle/$bundle/ \
            -cvf - "$bundle" | gzip -9 - > "$bundle.tar.gz"
      
      - run: ls -la
    
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "$bundle.tar.gz"