name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # softprops/action-gh-release needs this permission
    steps:
      - if: github.ref_type == 'branch'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Use workflow from a tag')

      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "beta"
      - name: Build
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter config --enable-linux-desktop
          flutter build linux --release

      - name: Package
        run: |
          pkg="tachidesk-flutter-${{ github.ref_name }}-linux-x64"
          tar --transform "s/bundle/$pkg/" -cvf - \
            -C build/linux/x64/release bundle | gzip -9 - > "$pkg.tar.gz"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: tachidesk-flutter-*
